stages:
  - test
  - build

unittest: 
  stage: test
  image: python:3-slim
  script: 
    - pip install - requirements.txt
    - python3 -m unittest discover
  tags:
    - docker

Docker build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} 192.168.190.75
    - docker build -t 192.168.190.75/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:/${CI_COMMIT_REF_SLUG} .
    - docker push 192.168.190.75/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:/${CI_COMMIT_REF_SLUG}
  tags:
    - docker


